Fix timestamp on the timeseries based charts (UTC -> LOCAL TZ)
Guavus/incubator-superset pull request #270
Opened 2019-11-12 18:10 UTC by subham-sarkar-guavus

The previous behaviour on the time series based charts was that the time was represented in UTC which wasn't user-friendly.

After the fix, the timestamp is shown in local timezone which is taken from the browser of the client. 

### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### Before:

Chart:
<img width="1440" alt="Before 1" src="https://user-images.githubusercontent.com/51480165/68697674-56123d00-05a5-11ea-9fad-6c0b9a72ba23.png">

Query:
<img width="1440" alt="Before 2" src="https://user-images.githubusercontent.com/51480165/68697697-62969580-05a5-11ea-9919-084012de331a.png">

### After:

Chart:
<img width="1440" alt="After 1" src="https://user-images.githubusercontent.com/51480165/68697712-6aeed080-05a5-11ea-9487-8f059b8519c4.png">

Query:
<img width="1440" alt="After 2" src="https://user-images.githubusercontent.com/51480165/68697718-6d512a80-05a5-11ea-93ea-6be5b21162b3.png">

### TEST PLAN

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

2019-11-14 09:06 UTC, subham-sarkar-guavus commented on superset/templates/appbuilder/footer.html
> +      <label class='footer-left-label'>SERVER TZ: {{ timezone }}</label>
Yes. Suggest me the name, I'll do it. Timezone mentioned there was full of conflict, whether it's the timezone where the Superset server is hosted or the timezone of the client from where superset is accessed. So added the prefix there.

2019-11-14 09:12 UTC, subham-sarkar-guavus commented on superset/db_engine_specs.py
> +            sub_expr = 'from_utc_timestamp(from_unixtime(%s), \'%s\')' % (expr, timezone)
Worked for most of the SQL based DBs (Maybe all).
For example, works with, MySQL, Hive, MariaDB, Postgres, etc.

Ref: https://www.tutorialspoint.com/sql/sql-date-functions.htm

You can find all the functions I've used here, so it's not hive specifically.

Plus, consider using `DIV` and not `\` also helps as when the format of unix_timestamp is in epoch_ms we divide it by 1000 and then do the query. So using `DIV` works for all given the fact that `\` fails for Hive. So, after making the changes, we're good to go for `epoch_ms` formats as well.

2019-11-14 09:16 UTC, subham-sarkar-guavus commented on superset/templates/appbuilder/footer.html
> +      <label class='footer-left-label'>SERVER TZ: {{ timezone }}</label>
Writing UTC every time is very misleading. Suppose if the server's in `America/New York` timezone, and for the calculations, it'll pick that. Although, I have pointed out changes to make it UTC always, in another PR. So, the differences of the relativeness for `epoch_s` and `epoch_ms` timestamps are taken relative from UTC which is correct for all further calculations. I've also verified the data manually from hive, and the output's satisfactory.

So, writing UTC is misleading client-side users.

2019-11-14 09:22 UTC, subham-sarkar-guavus commented on superset/db_engine_specs.py
> +            sub_expr = 'from_utc_timestamp(from_unixtime(%s), \'%s\')' % (expr, timezone)
Also, prior to this, the `epoch_to_dttm` used to return this `from_unixtime(unix_timestamp(from_unixtime(bin_time)), 'yyyy-MM-dd HH')`, I'm just using this one, `from_unixtime(unix_timestamp(from_utc_timestamp(from_unixtime(bin_time), 'Asia/Calcutta')), 'yyyy-MM-dd HH')`. Hence, no issues.

2019-11-20 04:49 UTC, subham-sarkar-guavus commented on superset/db_engine_specs.py
> +            sub_expr = 'from_utc_timestamp(from_unixtime(%s), \'%s\')' % (expr, timezone)
I've resolved some issues that could've broken this code. Also, as per the suggested I'm using the usual `epoch_to_dttm()` only. Hope the changes look good. They also passed all the UTs.

2019-11-21 16:41 UTC, arpit-agarwal commented on superset/templates/appbuilder/footer.html
> +      <label class='footer-left-label'>SERVER TZ: {{ timezone }}</label>
Is this actually a server timezone?
If yes i would say `Application Timezone`.
However in context of other PR it become irrelevant.
Assuming both will be merged together we can discuss what should be suffix

2019-11-21 17:17 UTC, arpit-agarwal requested changes
I need to understand overall flow and scope of this PR.
This seems to doing lot more than just timeseries time in local timezone

2019-11-21 17:17 UTC, arpit-agarwal commented on superset/connectors/sqla/models.py
> +        return [literal_column(expr, type_=DateTime).label(label), literal_column(self.expression or self.column_name)]
Is this relevant to changes for showing client timezone in timeseries

2019-11-22 05:44 UTC, arpit-agarwal reviewed
#DYNAMIC TZ
`select to_utc_timestamp(from_unixtime(1389802875), from_unixtime(unix_timestamp(), "z"));`

We may need this is we don't know the timezone at which `from_unixtime` will convert to

2019-11-22 05:44 UTC, arpit-agarwal commented on superset/db_engine_specs.py
> +    def get_time_expr(cls, expr, pdf, time_grain, grain, timezone):
why we have added a redundant parameter

2019-11-22 05:44 UTC, arpit-agarwal commented on superset/viz.py
> +            'timezone': client_tz,
where this timzone property is used.
can you share a flow of method invocations that is stitching this e2e data flow

2021-02-25 18:23 UTC, closed without merging